# Generated by Django 5.0.7 on 2024-08-02 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(default='', max_length=255)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[''], size=None)),
                ('users_admin', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[''], size=None)),
                ('pfp', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(default='', max_length=255, null=True)),
                ('unique_id', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
    ]
